gateway:
  logger:
    pretty: true
    level: DEBUG
  accesslog:
    # log http 5xx errors by default
    status_code_filters:
      # Unknown - http.StatusInternalServerError
      - equals: 2
      # DeadlineExceeded - http.StatusInternalServerError
      - equals: 4
      # Unimplemented - http.StatusNotImplemented
      - equals: 12
      # Unavailable - http.StatusServiceUnavailable
      - equals: 14
  stats:
    flush_interval: 1s
    log_reporter: {}
  timeouts:
    default: 15s
  middleware:
    - name: clutch.middleware.authn
    - name: clutch.middleware.stats
    - name: clutch.middleware.validate
  listener:
    tcp:
      address: 0.0.0.0
      port: 8080
      secure: false
modules:
  - name: clutch.module.assets
  - name: clutch.module.authn
  - name: clutch.module.healthcheck
  - name: clutch.module.resolver
  - name: clutch.module.aws
  - name: clutch.module.envoytriage
  - name: clutch.module.k8s
  - name: clutch.module.kinesis
services:
  - name: clutch.service.aws
    typed_config:
      "@type": types.google.com/clutch.config.service.aws.v1.Config
      regions:
        - us-east-1
        - us-west-2
  - name: clutch.service.envoyadmin
    typed_config:
      "@type": types.google.com/clutch.config.service.envoyadmin.v1.Config
      secure: false
      default_remote_port: 9876
  - name: clutch.service.k8s
    typed_config:
      "@type": types.google.com/clutch.config.service.k8s.v1.Config
  - name: clutch.service.authn
    typed_config:
      "@type": types.google.com/clutch.config.service.authn.v1.Config
      oidc:
        issuer: https://lyft.okta.com
        client_id: ${CREDENTIALS_OIDC_CLIENT_ID}
        client_secret: ${CREDENTIALS_OIDC_CLIENT_SECRET}
        redirect_url: "${BASE_URL}/v1/authn/callback"
      session_secret: ${CREDENTIALS_SESSION_SECRET}
      storage:
        encryption_passphrase: ${CREDENTIALS_AUTHN_ENCRYPTION_PASSPHRASE}

resolvers:
  - name: clutch.resolver.aws
  - name: clutch.resolver.k8s
