gateway:
  logger:
    pretty: true
    level: DEBUG
  accesslog:
    # log http 5xx errors by default
    status_code_filters:
      # Unknown - http.StatusInternalServerError
      - equals: 2
      # DeadlineExceeded - http.StatusInternalServerError
      - equals: 4
      # Unimplemented - http.StatusNotImplemented
      - equals: 12
      # Unavailable - http.StatusServiceUnavailable
      - equals: 14
  stats:
    flush_interval: 1s
    log_reporter: {}
  timeouts:
    default: 15s
  middleware:
    - name: clutch.middleware.stats
    - name: clutch.middleware.validate
  listener:
    tcp:
      address: 0.0.0.0
      port: 8080
      secure: false
modules:
  - name: clutch.module.assets
  - name: clutch.module.healthcheck
  - name: clutch.module.resolver
  - name: clutch.module.aws
  - name: clutch.module.envoytriage
  - name: clutch.module.k8s
  - name: clutch.module.kinesis
services:
  - name: clutch.service.auditsink.slack
    typed_config:
      "@type": types.google.com/clutch.config.service.auditsink.slack.v1.SlackConfig
      token: "foo"
      channel: "bar"
      filter:
        rules:
          - field: SERVICE
            text: clutch.k8s.v1.K8sAPI
          - field: SERVICE
            text: clutch.aws.ec2.v1.EC2API
      override:
        custom_slack_messages:
          - full_method: /clutch.k8s.v1.K8sAPI/ResizeHPA
            message: "`Min size` is {{.Request.Sizing.Min}} and `Max size` is {{.Request.Sizing.Max}}"
          - full_method: /clutch.k8s.v1.K8sAPI/DescribePod
            message: "Pod `{{.Request.Name}}` status is *{{.Response.Pod.State}}*"
          - full_method: /clutch.k8s.v1.K8sAPI/UpdateDeployment
            message: "Updated labels: {{slackList .Request.Fields `labels`}}"
          - full_method: /clutch.k8s.v1.K8sAPI/UpdatePod
            message: "Expected Preconditions: {{slackList .Request.ExpectedObjectMetaFields `annotations`}}"
  - name: clutch.service.aws
    typed_config:
      "@type": types.google.com/clutch.config.service.aws.v1.Config
      regions:
        - us-east-1
        - us-west-2
  - name: clutch.service.envoyadmin
    typed_config:
      "@type": types.google.com/clutch.config.service.envoyadmin.v1.Config
      secure: false
      default_remote_port: 9876
  - name: clutch.service.k8s
    typed_config:
      "@type": types.google.com/clutch.config.service.k8s.v1.Config
resolvers:
  - name: clutch.resolver.aws
  - name: clutch.resolver.k8s
