blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Ask a question
    url: https://github.com/lyft/clutch/discussions
    about: Ask questions and discuss with other community members
  - name: â“ General Inquiries
    about: Reach out to us in one of our other discussion channels.
    url: https://clutch.sh/docs/community/
